### ISSUE TITLE
Features, add minplayer to give AWp

### ISSUE THREAD

**Issue by MickaNoob** [yonilerner/cs2-retakes-allocator#101]
I'd like to share a feature with you.

1) Allow the addition of a minimum number of players required to activate AWP

2) And thus leave the possibility of activating grenades at pistols rounds/SMG rounds.

**Comment by everkk** [comment]
3. Add max awps per team

**Comment by Brazory** [comment]
First of all: I really like the PlugIn but i would add something to the suggestions above:

4. Give a decision for AWP with _**"sometimes"**_, beside the decisions  **_"always"_** and **_"never"_**, which you already have.

**Comment by MickaNoob** [comment]
it's not a bad idea ^^

**Comment by yonilerner** [comment]
Hey all, just wanted to let you know Ive not had a lot of time to work on this, but I have not forgotten. A new release is coming out tonight that has a ton of improvements, but I havent done this particular thing yet. Hopefully soon

**Comment by yonilerner** [comment]
With the latest version https://github.com/yonilerner/cs2-retakes-allocator/releases/tag/v2.3.1, all of these ideas are now implemented except for the "sometimes" option for AWP. Im honestly not sure how it should work, and Im not sure its worth adding.

If you get the AWP and decide you dont want it, you can always buy a different gun and use that instead.

Im gonna close this issue for now, but always feel free to open a new issue with suggestions!
