### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by everkk** [yonilerner/cs2-retakes-allocator#106]
Hello when i use !gun [weapon] on start round server insta crashing. I cant find anything in log about this.

**Comment by everkk** [comment]
Must be in same time when plugin allocate weapons

**Comment by RespawnGT** [comment]
+1

**Comment by yonilerner** [comment]
im so sorry, i am extremely overloaded at work right now, i am not sure when i can fix this. i will do my best to find time this weekend if im not doing my job over the weekend 😓
