### ISSUE TITLE
Weapons cannot be used - hands disappear

### ISSUE THREAD

**Issue by Doyapi808** [yonilerner/cs2-retakes-allocator#111]
New issue - after the end of the warmup, players will not get weapons - even after purchasing a weapon using the B button - the weapon will be displayed, but you cannot shoot from it and you don't even have hands
![Screenshot 2024-03-19 211436](https://github.com/yonilerner/cs2-retakes-allocator/assets/164083043/c64c9435-ee43-4c2b-b573-963cfe90fbe1)

**Comment by yonilerner** [comment]
I just updated the release with some new install instructions, hopefully that works. If that doesn't work, I would stick with the old release for now
