### ISSUE TITLE
Plugin not recognized by css.

### ISSUE THREAD

**Issue by LielXD** [yonilerner/cs2-retakes-allocator#112]
when the plugin loads it says "Unknown"
![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/60383662/3acbf8ac-1850-4c71-8641-9e8eb5b6274d)

any idea why it is like this?

**Comment by yonilerner** [comment]
I dont think this log is from this plugin. I would need to see more to be sure

**Comment by LielXD** [comment]
Nah its working good,
I just did something wrong.
