### ISSUE TITLE
Bug with latest version. 

### ISSUE THREAD

**Issue by MickaNoob** [yonilerner/cs2-retakes-allocator#121]
Impossible to pick up the opposing team's weapons. 

And you can't pick up the awp when it's on the ground, even your own.

![20240402170930_1](https://github.com/yonilerner/cs2-retakes-allocator/assets/20491694/853d0537-9e94-41a9-855f-5bfd785eecfe)

![20240402170327_1](https://github.com/yonilerner/cs2-retakes-allocator/assets/20491694/f840198b-3d4e-41e0-921d-ed1419614532)

Center bombsite announce is bugged, we got round type not bombsite announce.

AWP Limit, is working ! 
If you need another information.

**Comment by MickaNoob** [comment]
I think the bug might be related to Weapon Paint, but I'm not sure! 

https://github.com/Nereziel/cs2-WeaponPaints

**Comment by Fredgod23** [comment]
waiting for fix too

**Comment by yonilerner** [comment]
For the picking up weapons bug, this can be temporarily solved by undoing the new changes I did for the buy menu. set the `EnableCanAcquireHook` config to `false`. I am still working on a proper fix for this

The center round type announce can be turned off with `EnableRoundTypeAnnouncementCenter` set to `false`. Maybe that should be the default 🤔

**Comment by Fredgod23** [comment]
okok, it worked, thanks <3

**Comment by yonilerner** [comment]
Great. Ill update here once I have a proper fix so hopefully yall can re-enable this flag

**Comment by yonilerner** [comment]
This should be fixed in the latest release: https://github.com/yonilerner/cs2-retakes-allocator/releases/tag/v2.3.2

You can set `EnableCanAcquireHook` back to `true`
