### ISSUE TITLE
Request: Configurable chance for AWP

### ISSUE THREAD

**Issue by TropieRi** [yonilerner/cs2-retakes-allocator#122]
As currently with the plugin, if the round is determined to be a full buy round and the server has higher player count than what is defined in the config for AWP to be given, every full buy round is an AWP round as well. I'm suggesting to make a config for a % chance for a AWP to be given in a full buy round. So for example setting the % to 50 it means on every full buy round there is a 50% chance for AWP to appear. This would enable server owners to configure how often they want AWP to be played as it can be annoying to have AWP on every full buy round and it would more accurately simulate real game AWP amounts.

**Comment by yonilerner** [comment]
There is now a `ChanceForPreferredWeapon` config
