### ISSUE TITLE
[REQ] Make commands work with `/`

### ISSUE THREAD

**Issue by crashzk** [yonilerner/cs2-retakes-allocator#128]
Make commands work with `/`
- /gun <gun>
- /awp
- /guns

When we use commands with `/` nothing happens.

**Comment by GL1TCH1337** [comment]
It works with / already. As I saw your message on Discord. It related to CS2-Tags plugin. Issue should be closed.

**Comment by crashzk** [comment]
I could be wrong, but I tested it before even installing the CS2-Tags. In any case I will check again and confirm, if it is resolved by removing the CS2-Tags plugin I will close this issue.

**Comment by crashzk** [comment]
I removed the CS2 Tags plugin, but the commands `/guns`, `/gunsmenu` and any other plugin command using `/` don't work for me.

**CSS Plugins List**
```
  List of all plugins currently loaded by CounterStrikeSharp: 21 plugins loaded.
  [#1:LOADED]: "AFK Manager" (0.1.2) by NiGHT & K4ryuu (forked by Глеб Хлебов)
  [#2:LOADED]: "[VIP] Core" (v1.2.7) by thesamefabius
  [#3:LOADED]: "CustomCommands" (2.1.0) by HerrMagic
    Create your own commands per config
  [#4:LOADED]: "Reserved Slots" (1.0.6) by SourceFactory.eu
  [#5:LOADED]: "InventorySimulator" (1.0.0-beta.21) by Ian Lucas
    Inventory Simulator (inventory.cstrike.app)
  [#6:LOADED]: "[Custom] Plugin Commands Blocker" (V. 1.0.1 [Beta]) by Manifest @Road To Glory
    Prevents players from accessing your server's plugin information through the player console.
  [#7:LOADED]: "[VIP] Test" (v1.0.0) by thesamefabius
  [#8:LOADED]: "CSS-Panel" (1.5.0) by daffyy & Dliix66 & ShiNxz
    Simple admin plugin for Counter-Strike 2 :)
  [#9:LOADED]: "Retakes Plugin" (2.0.2) by B3none
    https://github.com/b3none/cs2-retakes
  [#10:LOADED]: "SteamGroupRestrict" (1.0.0) by BMathers
  [#11:LOADED]: "RockTheVote" (1.8.5) by abnerfs
    https://github.com/abnerfs/cs2-rockthevote
  [#12:LOADED]: "Clutch Announce Plugin" (1.1.0) by B3none
    Announce when someone wins a clutch scenario
  [#13:LOADED]: "Auto Map Changer" (1.0.8A) by skaen
  [#14:LOADED]: "High Ping Kicker" (0.0.6) by conch
    Kicks users with high ping
  [#15:LOADED]: "Retakes Allocator Plugin" (2.3.5) by Yoni Lerner, B3none, Gold KingZ
    https://github.com/yonilerner/cs2-retakes-allocator
  [#16:LOADED]: "Advertisement" (v1.0.6) by thesamefabius
  [#17:LOADED]: "AutoUpdater" (1.0.4) by dranix
    Auto Updater for Counter-Strike 2.
  [#18:LOADED]: "[VIP] Flags" (v1.0.0) by thesamefabius
  [#19:LOADED]: "Instadefuse Plugin" (1.4.3) by B3none
    Allows a CT to instantly defuse the bomb when nothing can prevent defusal.
  [#20:LOADED]: "Auto Delete Logs" (1.0.2) by Gold KingZ
    Auto Delete Logs Files
  [#21:LOADED]: "Faceit teammates damage modify" (1.0) by HoanNK
```

**Meta List**
```
Listing 3 plugins:
  [01] GOTVCrashFix (1.0.0) by Poggu
  [02] CounterStrikeSharp (v213 @ dfc9859) by Roflmuffin
  [03] ServerListPlayersFix (1.0.0.0) by Poggu
```

I believe it is due to the configuration of the file **[config.json](https://github.com/yonilerner/cs2-retakes-allocator/files/15085199/config.json)** that I use.

As you can see in the screenshot below, the commands themselves were not registered with `/`. I'll test registering them to see
![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/32937653/da66dd70-ea59-43d7-bf14-b4e67c68b85c)

If so, I believe that what can be done in future versions is to improve this feature, type only the commands that we want to use in the plugins and it will automatically work with `!` and `/`.

**Comment by GL1TCH1337** [comment]
@crashzk Sorry for misunderstanding. I have only tried /awp as I'm not using guns command myself. As you said they dont work with /. If you add /guns to the config it should work. Because the plugin not working with CS# command system. It checks chat messages.

**Comment by yonilerner** [comment]
This should be working now
