### ISSUE TITLE
[REQ] Option to change the color of the Retake prefix

### ISSUE THREAD

**Issue by crashzk** [yonilerner/cs2-retakes-allocator#131]
It would be interesting to have the option to fully configure the Retake prefix, color, space, etc.

Currently we only change the name from what I noticed:
```
  "ChatMessagePluginName": "Retakes",
  "ChatMessagePluginPrefix": null,
```

Support for changing color would be interesting too, why not include it in the translation too.

**Comment by crashzk** [comment]
Even after the PR: https://github.com/yonilerner/cs2-retakes-allocator/pull/137 merged I still can't change the color of the prefix.

I tested it like this and nothing, the colors are not applied, it shows the name of the colors.![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/32937653/aadafeb0-6cad-446b-ad04-f10574cc7cab)

**Comment by yonilerner** [comment]
You need to put in in ChatMessagePluginPrefix

**Comment by GL1TCH1337** [comment]
@crashzk 

```json
"ChatMessagePluginName": "Retakes",
"ChatMessagePluginPrefix": "[GREEN] quickplay.gg [NORMAL]",
```

**Comment by yonilerner** [comment]
It this still an issue or can we close?

**Comment by crashzk** [comment]
Oops, sorry for the delay, yes everything is ok now. We can close this issue.
