### ISSUE TITLE
[BUG] Compatibility with the CS2 Tags plugin

### ISSUE THREAD

**Issue by crashzk** [yonilerner/cs2-retakes-allocator#144]
I'm using this Allocator together with the plugin [CS2 Tags](https://github.com/schwarper/cs2-tags) by author **schwarper**.

When CS2 Tags is active on the server, the `!guns` and any other plugin commands do not work. There is no return in chat, for example, `!guns` should open the weapons menu in chat, but nothing happens.

I disabled CS2 Tags and that resolved the issue, everything works normally with it. Could this BUG be a problem with Allocator itself, or do we need to talk to the author of CS2 Tags?

**Comment by crashzk** [comment]
![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/32937653/86a1ce22-9e6d-4d71-8525-180e25a47d7d)

I believe we hope to wait for a future fix, if anything I will open this issue again.

**Comment by yonilerner** [comment]
Do you know why its not compatible with CS2 Tags? I am not familiar with that plugin

Unfortunately Ive been sick lately and haven't had much time to debug issues

**Comment by crashzk** [comment]
From what I understand, if I'm right it's with the Tags plugin itself, in this case limitations so to speak.

![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/32937653/8944d101-5a9b-48c6-965b-eaaf93b109d0)

https://discord.com/channels/1160907911501991946/1228389732145303572/1235383162952093796

Other plugins would have the same problem as some users reported.
