### ISSUE TITLE
Player Count BUG

### ISSUE THREAD

**Issue by shaikhnedab** [yonilerner/cs2-retakes-allocator#151]
```sh
[Client]   id     time ping loss      state   rate name
[Client] 65535 [NoChan]    0    0 challenging      0 ''
[Client]    1    03:12    4    0     active 786432 ':umbrella2:𝟕𝐞𝐦𝐩𝐞𝐫'
[Client]    2    01:59    3    0     active 786432 'Shaikh Kebab'
[Client]    3    01:53   34    0     active 786432 '𝙂𝙧𝙚𝙮𝙈𝙖𝙩𝙍'
[Client] #end
```

plugin counting dc players as player on server (challegning) and giving awp with below config

```sh
 "MinPlayersPerTeamForPreferredWeapon": {
    "Terrorist": 2,
    "CounterTerrorist": 2
```

[might need to add check like this](https://github.com/NockyCZ/CS2-ReservedSlots/blob/85877126d286bbc8001e0ac82cdc6168be93af5e/ReservedSlots.cs#L76)

**Comment by yonilerner** [comment]
Thanks! This should be fixed by this commit: https://github.com/yonilerner/cs2-retakes-allocator/commit/6c69b3960918b064d56c76cda1488386ebe71c51

The next release will have this fix
