### ISSUE TITLE
Duplicate weapons at spawn (CT)

### ISSUE THREAD

**Issue by MickaNoob** [yonilerner/cs2-retakes-allocator#165]
Hello,
I noticed an error after updating the plugins, some weapons are duplicated. 
I think it's linked to the Weapons Paint Update, (They have added new feature to give different knife for T and CT) and it affects the allocator. 

![20241103213004_1](https://github.com/user-attachments/assets/2e90bb7d-e73f-4181-8aeb-f31ffb5d5ce7)
![20241103145110_1](https://github.com/user-attachments/assets/25de36ad-3254-451b-b5ab-d7dd93c5a689)
![20241103145709_1](https://github.com/user-attachments/assets/042b33de-b790-484d-981c-cf52b68aacd0)

**Comment by AxxSabrina** [comment]
i want to know how to fix it too. but i don't think is Weapons Paint's problem,maybe we should talk about this orz...
