### ISSUE TITLE
Help configure DATHOST database

### ISSUE THREAD

**Issue by Fredgod23** [yonilerner/cs2-retakes-allocator#166]
Hello, I'm having some difficulties saving the options in the database, if I leave the default settings with Sqlite it doesn't work. However, I don't know how to configure it using phpmyadmin data. I may be just being stupid but I would appreciate some help.

**Comment by MickaNoob** [comment]
`"DatabaseConnectionString": "Server=xxxxxx;Port=3306;Database=xxxxx;Uid=xxxxx;Pwd=xxxxxx"`

Replace XXX by your information

**Comment by Fredgod23** [comment]
it worked, thanks <3
