### ISSUE TITLE
[Question] Why is the plugin using CustomGameData.cs, instead of that of CounterStrikeSharp?

### ISSUE THREAD

**Issue by tk1114632** [yonilerner/cs2-retakes-allocator#173]
Such as givenameditem, which is already implemented in CS#.

**Comment by yonilerner** [comment]
Using GiveNamedItem broke skins for people, im happy to change it if its no longer an issue. Ill also accept a PR to fallback to GiveNamedItem if GiveNamedItem2 breaks. I may have time to do it myself next week, not sure yet

**Comment by yonilerner** [comment]
Please see this release: https://github.com/yonilerner/cs2-retakes-allocator/releases/tag/v2.4.0 I believe it will help you out

**Comment by tk1114632** [comment]
Good job. Appreciate your works.
