### ISSUE TITLE
Bug: No Pistol Rounds, Plus FullBuy Round Weapon Stays in Pistol if Forced

### ISSUE THREAD

**Issue by KillerRoi** [yonilerner/cs2-retakes-allocator#24]
There are literally no pistol rounds, also on top of that other weapons are allowed even though it's not enabled in the config.

anybody can buy awps, make it so it automatically gives AWP to player who gets high kills or who has VIP tag.

**Comment by st1ng2** [comment]
I confirm that there are only full buy rounds. Round type percentages are set: 90 for pistol, 5 for half, 5 for full.

**Comment by yonilerner** [comment]
AWP queue is a separate thing that will require a lot of work that I haven't gotten to yet. I will look into the buy rounds situation though

**Comment by KillerRoi** [comment]
Can you atleast limit it to 1 AWP per team?

**Comment by KillerRoi** [comment]
With VIP and people with admin perms having override? Or just let the
players with perms buy the AWP or only they can get it

**Comment by yonilerner** [comment]
When I have time

**Comment by yonilerner** [comment]
> other weapons are allowed even though it's not enabled in the config.

@KillerRoi Can you show me your exact config?

**Comment by yonilerner** [comment]
@KillerRoi @st1ng2  https://github.com/yonilerner/cs2-retakes-allocator/pull/28 should have fixed the issue with only rifle rounds being chosen.

For the other issues reported here:
- "other weapons are allowed even though it's not enabled in the config" - please open a new issue with the exact config so I can debug it
- AWP limiting - see https://github.com/yonilerner/cs2-retakes-allocator/issues/29
- AWP VIP - see https://github.com/yonilerner/cs2-retakes-allocator/discussions/31

**Comment by st1ng2** [comment]
> @KillerRoi @st1ng2 #28 should have fixed the issue with only rifle rounds being chosen.
> 
> For the other issues reported here:
> 
> * "other weapons are allowed even though it's not enabled in the config" - please open a new issue with the exact config so I can debug it
> * AWP limiting - see [Configure # AWPs per team #29](https://github.com/yonilerner/cs2-retakes-allocator/issues/29)
> * AWP VIP - see [Increase AWP chances for VIPs #31](https://github.com/yonilerner/cs2-retakes-allocator/discussions/31)

I just tested latest version, now there is no half buy rounds (

**Comment by KillerRoi** [comment]
Check https://github.com/yonilerner/cs2-retakes-allocator/issues/42

**Comment by yonilerner** [comment]
@st1ng2 Can you share your exact config? Ill try to fix it today

@KillerRoi Please do not spam unrelated comments. I see all the issues and will deal with them when I have time

**Comment by KillerRoi** [comment]
You told me to open another issue for that, that's what I did 🙂

**Comment by yonilerner** [comment]
I think i found the issue, should be fixed in the next release
