### ISSUE TITLE
Configure # AWPs per team

### ISSUE THREAD

**Issue by yonilerner** [yonilerner/cs2-retakes-allocator#29]
Options:
- 1 per team
- Unlimited per team

**Comment by B3none** [comment]
Perhaps set it as a configurable value: `"MaxAwpsPerTeam": 1`. We also need to consider fallback weapon allocation so it might be worth implementing AWP allocation slightly differently.

**Comment by yonilerner** [comment]
I thought about that but I felt it wasn't a particularly valuable thing. Maybe I'm wrong. Heres my thought process.

- 95+% of servers want 1 AWP per team, *or* maybe 2 AWPs if the team is big. So these people would set this value to 1, but wish that they could have it be more flexible.
- ~5% of servers want AWPs to be unlimited. These people will set it to whatever their # slots is
- Almost no one specifically wants 2 AWPs *always*

So I figured if we did options like
```cs
enum AwpAllocationPolicy {
  ONE_PER_TEAM,
  UNLIMITED,
}
```
then later I could add a 3rd `SCALES_WITH_TEAM_SIZE` option if there was demand, and that would be like `num_awps =  floor(max(num_players - 1, 0) / 3) + 1`

**Comment by yonilerner** [comment]
At this point I dont think this level of complexity is necessary, and Ive already implemented the `MaxPreferredWeaponsPerTeam` config

**Comment by B3none** [comment]
> At this point I dont think this level of complexity is necessary, and Ive already implemented the `MaxPreferredWeaponsPerTeam` config

Can you give an example of how it works at the minute? This is a pretty important feature imo

**Comment by yonilerner** [comment]
pretty straightforward:
```json
  "MaxPreferredWeaponsPerTeam": {
    "Terrorist": 1,
    "CounterTerrorist": 1
  },
```
