### ISSUE TITLE
other weapons are allowed even though it's not enabled in the config

### ISSUE THREAD

**Issue by KillerRoi** [yonilerner/cs2-retakes-allocator#42]
`{
  "UsableWeapons": [
    "Deagle",
    "AK47",
    "M4A1S",
    "M4A1",
    "GalilAR",
    "SG556",
    "AWP",
    "SSG08"
  ],
  "AllowedWeaponSelectionTypes": [
    "PlayerChoice",
    "Random",
    "Default"
  ],
  "RoundTypePercentages": {
    "Pistol": 40,
    "HalfBuy": 0,
    "FullBuy": 60
  },
  "MigrateOnStartup": true
}
`

Here's my config.

**Comment by B3none** [comment]
If this is related to them showing in the guns menu I've sorted that now

**Comment by KillerRoi** [comment]
> If this is related to them showing in the guns menu I've sorted that now

It was something else, the guns which were supposed to be not allowed were allowed in Pistol rounds. For eg: it's a pistol round and everybody has AK and M4!😂
