### ISSUE TITLE
Round Type Ordering

### ISSUE THREAD

**Issue by CasaRica** [yonilerner/cs2-retakes-allocator#50]
In the RetakesAllocator plugin, is it possible to place for example, 5 pistol rounds, 10 half buys and 15 full buys? In other words, define by number of rounds?

**Comment by shaikhnedab** [comment]
+1 for this

**Comment by yonilerner** [comment]
I have a PR open for this but I havent properly tested it yet. If someone wants to test it out for me Id be very appreciative :slight_smile: 

The PR is here: https://github.com/yonilerner/cs2-retakes-allocator/pull/76 You can download the latest build straight from the PR by clicking on "Details" to the right of "Build RetakesAllocator.zip / build (pull_request)" (see attached screenshot). The latest right now is https://github.com/yonilerner/cs2-retakes-allocator/actions/runs/7579177634?pr=76 but that could change if I make more changes
![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/278810/5b5ffdd0-13c0-4bdc-af89-5776b3e96132)


Instructions for how to use the new config are in the README on the PR, here: https://github.com/yonilerner/cs2-retakes-allocator/pull/76/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I posted on the Discord also [here](https://canary.discord.com/channels/1160907911501991946/1193311939862986792/1197749057792258188).
