### ISSUE TITLE
Issue with Buy Menu

### ISSUE THREAD

**Issue by evenbreak** [yonilerner/cs2-retakes-allocator#84]
So fast forward, If i turn on buy menu, So well, when i buy using buy menu which is more convinent, it would be great to disable the commands !gun !guns(have a command for that or just toggle)

or just use the buy menu so it wont interfier with !gun !guns (since it wont work as i want, i cant buy m4a4 if i have m4a1s selected for example, kelver and helmet t side isnt showing, u have to buy it, and sometimes u start the round without anything(gun, knife, everything), you gotta buy it before it starts

![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/149022728/e1e78b78-db47-4a2e-8d01-e192baeca44c)

which you can see here

this only happens if i have the b menu activated by using , if i disable mp_buy_anywhere it goes back to normal

and also if i have AllowedWeaponSelectionTypes as 'Default' then it does not work at all

mp_buy_anywhere 1
mp_buytime 10
mp_maxmoney 65535
mp_startmoney 65535
mp_afterroundmoney 65535

**Comment by yonilerner** [comment]
Thanks for making an issue! Lets see if I can help with these.

- I have plans to make all of the commands configurable, so you can disable them if they conflict.

- I do specifically say in the README that for the buy menu to work, you need to have your convars set correctly. If you disable `mp_buy_anwhere` for example, it will not work, and I cannot change that. I don't want to override server settings, its up to the server owner to configure how they want it to work.

- You should always have kevlar on pistol rounds and kevlar + helmet on other rounds unless your convars are disabling that for some reason, or you have no `AllowedWeaponSelectionTypes` set (meaning you get NOTHING). This is explained in the README

- `AllowedWeaponSelectionTypes` configures how weapons are allocated. If you want people to be able to use the buy menu, it needs to be set to `"PlayerChoice"`

**Comment by yonilerner** [comment]
Im going to close this issue to keep things clean, but feel free to reopen it.

**Comment by ThomasAdnum** [comment]
Hi there, I am having the same/similar issue. 

I select Default as the config type, expecting everyone to get the Ak/M4 that ive set. However players spawn with nothing. 

![image](https://github.com/yonilerner/cs2-retakes-allocator/assets/31847081/d38e4d75-f830-4039-9d80-16a3b1c307dd)

I have selected Default on RoundTypeSelection, so I dont know why its spawning with nothing.

**Comment by yonilerner** [comment]
Please open a new issue and show your entire config and your retakes config
