### ISSUE TITLE
Buy menu weapon drop bug

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [yonilerner/cs2-retakes-allocator#86]
He's using the buy menu. Buys a deagle, and then it drops his main weapon and the 2nd weapon he had also disappears, and he never gets the deagle either. Bug? Or I'm using some weird setting that is causing this? If so what?

Video:
https://discord.com/channels/1160907911501991946/1193311939862986792/1200719109327958149

**Comment by yonilerner** [comment]
Sorry youre having issues, please provide the entire JSON config to help me figure out the problem.

**Comment by yonilerner** [comment]
Im going to close this issue to keep things clean, but feel free to reopen it.
