### ISSUE TITLE
Prefix "[Retakes] "

### ISSUE THREAD

**Issue by CasaRica** [yonilerner/cs2-retakes-allocator#91]
The possibility of changing the [Retakes] tag for example in the config.

**Comment by yonilerner** [comment]
seems reasonable

**Comment by yonilerner** [comment]
Done in https://github.com/yonilerner/cs2-retakes-allocator/commit/9710eb8b7bf5f65b57704c8c05afe6b192c9e2cf . Will go out in the next release when I can update the plugin to the next CS# version that isn't broken
