### ISSUE TITLE
AWP and Stuff limitation

### ISSUE THREAD

**Issue by kingdragox99** [yonilerner/cs2-retakes-allocator#92]
can you add awp and stuff limitation ?

**Comment by yonilerner** [comment]
Id like to help but I dont really understand. Can you be more specific about what youre asking for?

**Comment by kingdragox99** [comment]
1. The ability to set a maximum number of awp per round for CTs and Ts.

2. You can cap the maximum amount of stuff you can buy per round.

example: I've set the maximum amount of money to 800$, so CTs and Ts can't buy/get more than 800$ worth of stuff per round.

**Comment by yonilerner** [comment]
1 is something im thinking about over here if you want to give your thoughts: https://github.com/yonilerner/cs2-retakes-allocator/issues/29

As for the 2nd, I dont think thats really the style of how this allocator works. The idea of this allocator is to give players automatically what they want to use for the round. Having players purchase their entire kit at the start of every round would be a pretty different experience

**Comment by kingdragox99** [comment]
I don't think that in that way: more like random stuff for 800$ per player like 2 flashes + 1 smoke or 1 molo 1 flash. players can't buy it.

Because all too often we find ourselves in situations where if the T's have 3 molo 4 smoke and the CT's have 4 molo 8 flash and 2 smoke, it's just unplayable.

**Comment by yonilerner** [comment]
@kingdragox99 Do the ideas here solve the problems you have? https://github.com/yonilerner/cs2-retakes-allocator/discussions/21

**Comment by kingdragox99** [comment]
yes

**Comment by yonilerner** [comment]
Thanks for your feedback. Im going to close this issue then since that work is already tracked in #21 and #29. #21 in particular should be basically complete in the latest release
